name: Configure Github

on:
    push:
        branches:
            - main

env:
    # verbosity setting for Terraform logs
    TF_LOG: INFO
    # Credentials for deployment to AWS
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
    terraform:
        name: AWS Github OpenID Connector
        runs-on: ubuntu-latest

        steps:
            - name: Setup Terraform with specified version on the runner
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: 1.5.7

            - name: Checkout the repository to the runner
              uses: actions/checkout@v4

            - name: Change directory
              run: cd terraform

            - name: Terraform init
              id: init
              run: terraform init

            - name: Terraform format
              id: fmt
              run: terraform fmt -check

            - name: Terraform validate
              id: validate
              run: terraform validate

            - name: Terraform plan
              id: plan
              if: github.event_name == 'pull_request'
              run: terraform plan -no-color -input=false
              continue-on-error: true
